### ISSUE TITLE
Can't get report a problem to work

### ISSUE THREAD

**Issue by neoinsight** [neoinsight/prototypes#1]
@shawnthompson Help! I copied the code snippet for Report a problem from this page http://servicecanada.github.io/GCWeb/home-fr.html into this page in this repo: http://neoinsight.github.io/prototypes/experimental/contacts-en.html

It looks pretty good but it isn't opening up a dialog box when you check an item, so I must have missed something. Can you advise please?  Have not yet made the change to the French page yet. 

I am making a page with an obvious problem (see the first item under the Benefits contacts) to see if I can get participants to use the button.  Thanks.

**Comment by shawnthompson** [comment]
It's missing the theme.min.js at the bottom of the page.

`<script src="./GCWeb/js/theme.min.js"></script>`

**Comment by shawnthompson** [comment]
add that right before the `</body>` tag

**Comment by neoinsight** [comment]
@shawnthompson Oh darn, that still isn't working. Did you change the css or something? (I put in src="../GcWeb..." because this code is in the Experimental folder.

**Comment by shawnthompson** [comment]
You have the latest stable release. The change for the [Development releases](http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html#v40dev) package. 

If you open up one of the `css` or `js` files, you should look for the following in the comments.

```
v4.0.22-development - 2016-06-21
```

**Comment by shawnthompson** [comment]
I would put your page in the root and not the _experimental_ folder, I'm not even sure why that's there.

**Comment by neoinsight** [comment]
Oh! Ok, will try that. Thanks  (copying @steve-h )

**Comment by shawnthompson** [comment]
I'm having a training session for WET next week on Wednesday. Do you or @steve-h want to join?

**Comment by shawnthompson** [comment]
I've added you to the invite, you can share it with @steve-h

**Comment by neoinsight** [comment]
Thanks (clearly need the training...)
