### ISSUE TITLE
Need Canada.ca footer in prototypes

### ISSUE THREAD

**Issue by neoinsight** [neoinsight/prototypes#3]
@shawnthompson We are using these prototypes for usability testing (and sometimes prototypes in the gcweb repo), so it would be much preferred if the new Canada.ca footer was available to use in the pages we create. 

Have talked to @steve-h about doing this - can you advise on whether you will be updating the gcweb repo that this was originally forked from? It was created following the advice from Codefest you posted here: http://shawnthompson.github.io/jekyll-presentation/2016/02/15/gh-pages.html

Or maybe you could add instructions to that post about how to keep the WET in protoyping repos up to date?

Thanks!

**Comment by shawnthompson** [comment]
There's no easy way to keep it in sync with the GCWeb repo. You will have to create a new repo every time you want to create a new prototype.

That's what I do here:

https://github.com/ServiceCanada/

Notice all the repos that are named **GCWeb-**something...

I grab a new copy of the zip file from the [WET download page](http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html), make a git repo out of it and push it to Github as a `gh-pages` branch.

It becomes second nature after you do a few.

Hope this helps

**Comment by neoinsight** [comment]
@shawnthompson Thanks so much - @steve-h built a new repo for me and it has the updated footer design. 
It will become second nature to him I hope ;)
